# Generated by Django 3.1.2 on 2020-10-08 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nexxera_api', '0003_auto_20201008_1325'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='operation',
            field=models.CharField(choices=[('DEBIT', 'Debit.'), ('CREDIT', 'Credit.')], max_length=64, verbose_name='operation'),
        ),
        migrations.AlterIndexTogether(
            name='account',
            index_together={('account', 'branch', 'balance')},
        ),
        migrations.AlterIndexTogether(
            name='transaction',
            index_together={('account', 'operation', 'value')},
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='status',
        ),
    ]
